[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

# Estrutura corrigida para as funções
[functions]
  node_bundler = "esbuild"

[functions.mapa]
  node_version = "22"

[functions.verificarsessao]
  node_version = "22"

[dev]
  framework = "vite"
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
